Fix/table alignment
metrumresearchgroup/pmforest pull request #14
Opened 2022-03-04 23:10 UTC by barrettk

2022-03-04 23:12 UTC, barrettk commented
New plot looks much nicer:
![image](https://user-images.githubusercontent.com/18685116/156854425-c2cfd96f-da3d-47e3-af3d-36cf0e5fc6ac.png)

This PR is still WIP, as the alignment fix ruined the last PR I made that addressed multi-lined table headers

2022-03-07 18:43 UTC, barrettk commented
Multiple lines can now be entered for `CI_label`, without messing up the alignment:
![image](https://user-images.githubusercontent.com/18685116/157097547-72c246ae-44ae-450a-abb4-163fa2be4c18.png)

2022-03-07 21:11 UTC, seth127 requested changes
This all looks good, just a few small changes (nothing to the code).

I do want to add tests for this from https://github.com/metrumresearchgroup/pmforest/issues/11#issuecomment-1054500429
> Another key test will be when you change the size of the plot

but I think that's going to be non-trivial. Let's move ahead with this and I might start another branch with that test if I can figure out how.

2022-03-07 21:42 UTC, barrettk commented on NEWS.md
> +# pmforest 0.0.2
@seth127 bbr has version numbers though. Do we just update the version at the _next_ release?

2022-03-07 21:47 UTC, barrettk commented on NEWS.md
> +# pmforest 0.0.2
Misunderstood at first. Will change

2022-03-07 21:47 UTC, barrettk commented on NEWS.md
> +* `shapes` argument. Will denote the shape of the mean/median value. Users can specify one of the following: "square", "diamond", "circle", or "triangle".
Done

2022-03-07 21:48 UTC, barrettk commented on R/forest-constructor.R
>    # copied this from ggpubr::as_ggplot() so to not need ggpubr (and specifically nloptr)
The part you quoted is not longer in the code, but ill remove mentions of cowplot

2022-03-07 21:52 UTC, barrettk commented on R/table-plot.R
> +      geom_hline(yintercept = y_lines - 0.3) + #max(plotdata$ID) + 2.1) +
This was addressed in a later commit

2022-03-07 21:53 UTC, barrettk commented on R/table-plot.R
> +    # # Add extra space to y_limit depending on number of lines in table title
Yeah - I misunderstood the problem multiple times, but once the issue became clear it was much easier to simplify the existing code, and a complete refactor wasnt necessary

2022-03-08 14:35 UTC, seth127 approved these changes
Looks good. After you merge this, check out #15 for me.

2022-03-08 15:19 UTC, merged